name: Collate metadata

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 2"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-r@v2
      with:
        install-r: false
        use-public-rspm: true

    - name: Install R system requirements
      run: |
        sudo apt-get install pandoc libcurl4-openssl-dev

    - uses: r-lib/actions/setup-renv@v2

    - name: Create metadata status page
      run: |
        Rscript -e 'rmarkdown::render("data-processed/README.Rmd")'

    - name: Commit files
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action - collate metadata"
        git add --all
        git commit -m "Collate metadata"
        git pull --rebase origin main
        git push
        echo "pushed to github"

    - name: Create issue about failure
      if: failure() && github.event_name != 'workflow_dispatch'
      uses: JasonEtco/create-an-issue@v2.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/action-issue-template.md
