name: Validations v2

on:
  pull_request_target:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.2]

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'epiforecasts/covid19-forecast-hub-europe-validations'
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
#     - run: npm install
    - run: pip3 install -r requirements.txt
    - run: python3 main.py
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  link-preview:
    runs-on: ubuntu-20.04
    env:
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v1

    - name: Install system dependencies
      run: sudo apt-get install libudunits2-dev libcurl4-openssl-dev libgdal-dev

    - name: Install R dependencies
      run: |
        install.packages(c("remotes", "gh"))
        remotes::install_github("epiforecasts/EuroForecastHub")
      shell: Rscript {0}

    - name: Post comment linking to preview shiny app
      env:
        PR_NUMBER: ${{ github.event.number }}
      run: |
        links <- EuroForecastHub::link_preview(
          gh_repo = Sys.getenv("GITHUB_REPOSITORY"),
          pr_number = Sys.getenv("PR_NUMBER"),
          data_folder = "data-processed"
        )
        gh::gh(
          "/repos/{gh_repo}/issues/{pr_number}/comments",
          .method = "POST",
          gh_repo = Sys.getenv("GITHUB_REPOSITORY"),
          pr_number = Sys.getenv("PR_NUMBER"),
          accept = "application/vnd.github.v3+json",
          body = paste(c("Preview of submitted forecast:", links), collapse = "\n")
        )
      shell: Rscript {0}
