name: Zoltar upload

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'epiforecasts/covid19-forecast-hub-europe-validations'

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      run: - pip3 install -r requirements.txt
      run: - python3 code/zoltar_scripts/upload_zoltar.py

      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
